remove resolver.UnregisterForTesting usage
yarpc/yab pull request #417
Opened 2024-09-24 10:58 UTC by bananacocodrilo

`resolver.UnregisterForTesting` has been removed from grpc-go https://github.com/grpc/grpc-go/pull/6471, this change is needed in order to update to grpc 1.59.0

2024-09-24 10:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yarpc/yab?pullRequest=417) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yarpc/yab?pullRequest=417) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yarpc/yab?pullRequest=417) it.</sub>

2024-09-24 23:49 UTC, jronak approved these changes

2024-09-25 16:22 UTC, biosvs requested changes

2024-09-25 16:22 UTC, biosvs commented on protobuf/source_reflection.go
> +	r := GenerateAndRegisterManualResolver()
We're creating potential memory leak here.
Let's discuss potential solution with a custom resolver, i.e. to register only one resolver, and then reuse it for different services.

2024-09-26 13:16 UTC, bananacocodrilo commented on protobuf/source_reflection.go
> +	r := GenerateAndRegisterManualResolver()
I've looked into two options to address it:
 
 ### Keep the manual resolver.

We can create the scheme deterministically (I'm thinking `scheme = "dest-" + args.Service`).
This allows us to use `resolver.Get(scheme)` to avoid creating unnecessary resolvers, and we also can keep an updated the list of peers in the resolver.
 
 ### Use passthrough

This results in simpler code, but only allows to specify one peer.
If the peer-list file used contains outdated addresses this could make the reflection fail where otherwise it would have worked.

2024-09-30 15:49 UTC, bananacocodrilo commented on protobuf/source_reflection.go
> +		if r, ok := rb.(*manual.Resolver); ok {
Manual resolvers implement both, Resolver and Builder.
r.InitialState(newState) will set the new list of peers the next time that Build is called

2024-09-30 15:49 UTC, bananacocodrilo commented on protobuf/source_reflection_test.go
> +func TestResolverAlreadyExists(t *testing.T) {
Test creating a new resolver for the same service with a different list of peers

2024-10-01 11:00 UTC, biosvs commented on protobuf/source_reflection.go
> +			r.InitialState(newState)
InitialState doesn't use mutex inside, so it's a potential data race.

2026-02-11 10:02 UTC, closed without merging